# Generated by Django 2.2.5 on 2019-10-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191004_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
