# Generated by Django 2.2.5 on 2019-10-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191004_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
