# Generated by Django 2.2.5 on 2019-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default='default.svg', upload_to='upload'),
        ),
    ]
