# Generated by Django 2.2.5 on 2019-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191007_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
