# Generated by Django 2.2.5 on 2019-10-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191007_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveredOn',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
