# Generated by Django 2.2.5 on 2019-10-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191007_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='app.Order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MenuItem')),
            ],
        ),
    ]
