# Generated by Django 2.2.5 on 2019-10-08 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191008_0414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItems',
            new_name='OrderedItem',
        ),
    ]
