# Generated by Django 3.0.3 on 2020-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='couponKey',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
